all:

devops:
  children:
    deploymnet:
      hosts:
        hl1-deploy-01:
      vars:
        docker_users: 
          - ubuntu
        networks: 
          - monit-network
        docker: true
        docker_networks: true 
