all:

devops:
  children:
    deploymnet:
      hosts:
        hl1-deploy-01:
      vars:
        docker_users: 
          - ubuntu
        networks: 
          - monit-network

  # children:
  #   devops:
  #     children:
  #       devops_tools:
  #         hosts:
  #           hl1-deploy-01:
  #       vars:
  #         docker_users: ubuntu
  #         networks: monit-network
