---
- name: Run Linux Nomad Server Node Setup
  hosts: all
  gather_facts: yes
  become: yes

  roles:

    # Configuration and Management
    - name: Patch Linux Servers
      role: os_updates/linux
      tags: patch

    - name: Setup NFS on Server
      role: nfs_config
      tags: nfs-config

    # Docker Stuff
    - name: Install Docker
      role: docker/install_docker
      tags: install-docker

    - name: Add Docker Users
      role: docker/add_users
      tags: install-docker, add-docker-user

    - name: Add Networks to Docker
      role: docker/docker_networks
      tags: install-docker, docker-networks 

    # Nomand Server
    - name: Setup Linux Nomad Server Nodes
      role: nomad/linnomadsn
      tags: linnomadsn
    
    - name: Setup Linux Nomad Client Nodes
      role: nomad/linnomadcn
      tags: linnomadcn

    # Consul Configurations
    - name: Setup Linux Consul server
      role: consul/consul_server/linux
      tags: linconsul_server

    - name: Setup Linux Consul Agent 
      role: consul/consul_agent/linux
      tags: linconsul_agent
    
    # Monitoring Tools
    - name: Setup Influx
      role: devops/influxdb
      tags: influxdb

    # Registry
    - name: Setup Harbor
      role: devops/harbor
      tags: harbor