---
- name: Run Linux Nomad Server Node Setup
  hosts: all
  gather_facts: yes
  become: yes

  roles:

    # Configuration and Management
    - name: Patch Linux Servers
      role: linux/os_updates
      tags: patch

    - name: Setup NFS on Server
      role: linux/nfs_config
      tags: nfs-config

    # Docker Stuff
    - name: Install Docker
      role: linux/docker/install_docker
      tags: install-docker

    # - name: Add Docker Users
    #   role: linux/docker/sub_roles/add_users
    #   tags: docker-user

    # - name: Add Networks to Docker
    #   role: linux/docker/sub_roles/docker_networks
    #   tags: docker-networks 

    # Nomand Server
    - name: Setup Linux Nomad Server Nodes
      role: linux/nomad/server_node
      tags: linnomad_server
    
    - name: Setup Linux Nomad Client Nodes
      role: linux/nomad/client_node
      tags: linnomad_client

    # Consul Configurations
    - name: Setup Linux Consul server
      role: linux/consul/consul_server
      tags: linconsul_server

    - name: Setup Linux Consul Agent 
      role: linux/consul/consul_agent
      tags: linconsul_agent
    
    # # Monitoring Tools
    # - name: Setup Influx
    #   role: devops/influxdb
    #   tags: influxdb

    # # Registry
    # - name: Setup Harbor
    #   role: devops/harbor
    #   tags: harbor