---
- name: Ensure dependencies are installed
  apt:
    name: nfs-common
    state: present
    update_cache: yes

# Mount create storage directory on mount
- name: Ensure storage for {{ ansible_hostname }} directory exists under /mnt
  file:
    path: /mnt/storage
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Mount NFS storage for {{ ansible_hostname }} as /mnt/storage
  ansible.posix.mount:
    src: "{{ nfs_server }}:/mnt/storage_pool/servers/{{ ansible_hostname }}"
    path: "/mnt/storage"
    opts: rw,sync,_netdev
    state: mounted
    fstype: nfs

- name: Create subdirectories in storage directory
  file:
    path: "/mnt/storage/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - home
    - opt

- name: Sync existing directory contents to storage directory
  ansible.builtin.command: rsync -aAXv /{{ item.src }}/ /mnt/storage/{{ item.dest }}/
  loop:
    - { src: home, dest: home }
    - { src: opt, dest: opt }

- name: Remove old directories
  file:
    path: /{{ item }}
    state: absent
  loop:
    - home
    - opt

- name: Recreate directories
  file:
    path: /{{ item }}
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - home
    - opt

- name: Ensure bind mounts exist for /home and /opt
  ansible.posix.mount:
    src: "/mnt/storage/{{ item.src }}"
    path: "{{ item.dest }}"
    fstype: none
    opts: bind
    state: mounted
  loop:
    - { src: home, dest: /home }
    - { src: opt, dest: /opt }

- name: Ensure fstab entries exist for persistence
  blockinfile:
    path: /etc/fstab
    block: |
      {{ nfs_server }}:/mnt/storage_pool /mnt/storage nfs rw,sync,_netdev,noatime 0 0
      /mnt/storage/home /home none bind 0 0
      /mnt/storage/opt /opt none bind 0 0

- name: Create Docker directory
  include_tasks: docker.yml
  when: docker

- name: Create Nomad directories
  include_tasks: nomad.yml
  when: noamd