---
- name: Ensure dependencies are installed
  apt:
    name: nfs-common
    state: present
    update_cache: yes

# Mount create storage directory on mount
- name: Ensure storage for {{ ansible_hostname }} directory exists under /mnt
  file:
    path: "{{ mount_path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: '0777'

- name: Mount NFS storage for {{ ansible_hostname }} as /mnt/storage
  ansible.posix.mount:
    src: "{{ nfs_server }}:{{ nfs_path }}/servers/{{ ansible_hostname }}"
    path: "{{ mount_path }}"
    opts: rw,sync,_netdev
    state: mounted
    fstype: nfs

- name: Create subdirectories in storage directory
  file:
    path: "{{ mount_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - home
    - opt
    - var/log

- name: Sync existing directory contents to storage directory
  ansible.builtin.command: rsync -aAXv /{{ item.src }}/ {{ mount_path }}/{{ item.dest }}/
  loop:
    - { src: home, dest: home }
    - { src: opt, dest: opt }

- name: Remove old directories
  file:
    path: /{{ item }}
    state: absent
  loop:
    - home
    - opt

- name: Recreate directories
  file:
    path: /{{ item }}
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop:
    - home
    - opt

- name: Ensure bind mounts exist for /home and /opt
  ansible.posix.mount:
    src: "{{ mount_path }}/{{ item.src }}"
    path: "{{ item.dest }}"
    fstype: none
    opts: bind
    state: mounted
  loop:
    - { src: home, dest: /home }
    - { src: opt, dest: /opt }

- name: Ensure fstab entries exist for persistence
  blockinfile:
    path: /etc/fstab
    block: |
      {{ nfs_server }}:{{ nfs_path }} {{ mount_path }} nfs rw,sync,_netdev,noatime 0 0
      {{ mount_path }}/home /home none bind 0 0
      {{ mount_path }}/opt /opt none bind 0 0

- name: Extra directory creations for Nomad Clients
  include_tasks: nomad_client.yml
  when: nomad_client



# - name: Create Docker directory
#   include_tasks: docker.yml
#   when: 
#     - nomad or docker

# - name: Create Nomad directories
#   include_tasks: nomad.yml
#   when: nomad

# - name: Create Consul Server directories
#   include_task: consul_server.yml
#   when: consul_server

# - name: Create Consul Agent directories
#   include_task: consul_agent.yml
#   when: consul_agent or nomad