---
# Create and mount nomad directories
- name: Create nomad data directory on storage 
  file:
    path: "/mnt/storage/etc/nomad.d"
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: nomad

# Prep for Noamd installation for servers requiring nomad

- name: Create nomad.d directory
  file:
    path: /etc/nomad.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  when: nomad

- name: Bind mount nomad directory
  ansible.posix.mount:
    src: "/mnt/storage/etc/nomad.d"
    path: "/etc/nomad.d"
    fstype: none
    opts: bind
    state: mounted
  when: nomad

# Update fstab
- name: Ensure fstab entry exists for /mnt/storage/nomad
  blockinfile:
    path: /etc/fstab
    block: |
      /mnt/storage/etc/nomad.d /etc/nomad.d/ none bind 0 0
  when: nomad